#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Last revised: 15 February 2023
# eva_mn
# --------------------------------------------------------------------------------------------------

#SBATCH -J xyz-tgx-test                                 # SET THE JOB NAME!!!!!!!!!!!!
#SBATCH -o ../results/%x-%j.out                         # Name of stdout output file
#SBATCH -p p100                                         # Queue (partition) name
#SBATCH -N 1                                            # Total # of nodes
#SBATCH --ntasks-per-node 1                             # Total # of tasks per node (mpi tasks)
#SBATCH -t 00:05:00                                     # Run time (hh:mm:ss)
#SBATCH --mail-type=none                                # Send email at begin and end of job
#SBATCH -A Modeling-of-Microsca                         # Allocation name (req'd if you have more than 1)

start=$(date +%s)

# get job number and name for file saving in python script, set some params
set -a
jobid=${SLURM_JOBID}
jobname="${SLURM_JOB_NAME%".sh"}"
filename="$(basename -s .sh "$0")"
set +a    # only need to export job info vars

# !!!!!!!---------------------------------- SET INPUT VARS ----------------------------------!!!!!!!
test_dir="tgx_data/test/targets"
test_target_dir="tgx_data/test/targets"
data_info="TGX square pillars data, 41 varied speed images (taken 02.01.2023)\n"
channels=1

redux=0
noise="raw"
test_param=0.4

test_ckpt="ckpts/xyz-tgx-raw/xyz-tgx-raw0.4l2/xyz-tgx-raw0.4l2.pt"            # SET TEST CKPT!!!!!!!

# --------------------------------------------------------------------------------------------------

# get ckpt name (set substring to remove from jobname if necessary)
sub="-test"
# because idev jobs don't follow the rules for some reason
idev="idv"
if [[ $jobname == *"$idev"* ]]  
then
    spec_string="${filename%$sub}-${noise}"
    echo "This is an idev job, using filename in place of jobname to get spec string:"
else
    spec_string="${jobname%$sub}-${noise}"
    echo "Using jobname to get spec string:"
fi

results="results/${spec_string}"
echo "Results will be saved to: ${results}"

# --------------------------------------------------------------------------------------------------

echo -e "\nDate:  $(date)\n"

# get from SLURM env vars
echo -e "Begin batch job... \n \
    File Name:       ${filename} \n \
    Job Name:        ${jobname} \n \
    Job ID:          ${jobid} \n \
    Output file:     ${jobname}.out \n \
    Partition:       ${SLURM_JOB_PARTITION} \n \
    Nodes:           ${SLURM_JOB_NUM_NODES} \n \
    Ntasks per node: ${SLURM_TASKS_PER_NODE} \n \
    Dataset:         ${data_info}\n"

cd ..
echo -e "Working directory:  $(pwd)\n"

# for using conda environments in SLURM bash scripts
if [ $(( ! CONDA_SHLVL)) ]
then
    source /work/08261/evanat/maverick2/miniconda3/etc/profile.d/conda.sh
    conda activate imgrec
    # echo -e "conda is now initialized for this script and imgrec has been activated.\n"
else
    # conda is already initialized
    if [ "${CONDA_DEFAULT_ENV}" != imgrec ]
    then
        source /work/08261/evanat/maverick2/miniconda3/etc/profile.d/conda.sh
        conda activate imgrec
        # echo -e "the imgrec environment has been activated.\n"
    fi
fi


echo -e "Using python executable at: $(which python)\n\n"

# Launch testing code if training was successful
echo -e "\n----------------------------------------------------------------------------------------------\n"
echo -e "\nDate:  $(date)\n"

# Launch test code using virtual environment
python src/test.py \
    -t ${test_dir} \
    --target-dir ${test_target_dir} \
    -r ${redux} \
    -n ${noise} \
    -p ${test_param} \
    --output "${results}" \
    --load-ckpt "${test_ckpt}" \
    --ch ${channels} \
    --cuda \
    --montage-only \
    --paired-targets


end=$(date +%s)
runtime_hours=$(((end-start)/3600))
runtime_minutes=$((((end-start)%3600)/60))
runtime_seconds=$((((end-start)%3600)%60))
echo -e "\nBatch job runtime was ${runtime_hours}h:${runtime_minutes}m:${runtime_seconds}s.\n "
