#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Last revised: 5 April 2023
# eva_mn
# --------------------------------------------------------------------------------------------------

#SBATCH -o ../ckpts/%x-%j.out                           # Name of stdout output file
#SBATCH -p p100                                         # Queue (partition) name
#SBATCH -N 1                                            # Total # of nodes
#SBATCH --ntasks-per-node 48                            # Total # of tasks per node (mpi tasks)
#SBATCH -t 04:00:00                                     # Run time (hh:mm:ss)
#SBATCH --mail-type=none                                # Send email at begin and end of job
#SBATCH -A Modeling-of-Microsca                         # Allocation name (req'd if you have more than 1)

start=$(date +%s)

# get job number and name for file saving in python script, set some params
set -a
jobid=${SLURM_JOBID}
jobname="${SLURM_JOB_NAME%".sh"}"
filename="$(basename -s .sh "$0")"
set +a    # only need to export job info vars

# !!!-------------------------------------- SET INPUT VARS --------------------------------------!!!
data_name="combo_xyz_data"
train_dir="${data_name}/train"
valid_dir="${data_name}/valid"
target_dir="${data_name}/targets"
data_info="Combined TGX11 and HS20MG training data\n"
channels=1

train_ckpt=""    # for retraining a checkpoint (leave empty to create a new ckpt)

redux=0
noise="raw"
train_param=0.15
report=115
epochs=150
batch_size=12
loss_fun='l2'

# --------------------------------------------------------------------------------------------------
ckpt_spec="${train_param}${loss_fun}"

# get ckpt name (set substring to remove from jobname if necessary)
sub="-imgrec"
# because idev jobs don't follow the rules for some reason
idev="idv"
if [[ $jobname == *"$idev"* ]]  
then
    ckpt_string="${filename%$sub}-${noise}"
    echo "This is an idev job, using filename in place of jobname to find checkpoint:"
else
    ckpt_string="${jobname%$sub}-${noise}"
    echo "Using jobname to find checkpoint:"
fi

ckpt_save="ckpts/${ckpt_string}/${ckpt_string}${ckpt_spec}"

# --------------------------------------------------------------------------------------------------

echo -e "\nDate:  $(date)\n"

# get from SLURM env vars
echo -e "Begin batch job... \n \
    File Name:       ${filename} \n \
    Job Name:        ${SLURM_JOB_NAME} \n \
    Job ID:          ${SLURM_JOB_ID} \n \
    Output file:     ${SLURM_JOB_NAME}.out \n \
    Partition:       ${SLURM_JOB_PARTITION} \n \
    Nodes:           ${SLURM_JOB_NUM_NODES} \n \
    Ntasks per node: ${SLURM_TASKS_PER_NODE} \n \
    Dataset:         ${data_info}\n"

cd ..
echo -e "Working directory:  $(pwd)\n"


# for using conda environments in SLURM bash scripts
if [ $(( ! CONDA_SHLVL)) ]
then
    source /work/08261/evanat/maverick2/miniconda3/etc/profile.d/conda.sh
    conda activate imgrec
    # echo -e "conda is now initialized for this script and imgrec has been activated.\n"
else
    # conda is already initialized
    if [ "${CONDA_DEFAULT_ENV}" != imgrec ]
    then
        source /work/08261/evanat/maverick2/miniconda3/etc/profile.d/conda.sh
        conda activate imgrec
        # echo -e "the imgrec environment has been activated.\n"
    fi
fi


echo -e "Using python executable at: $(which python)\n\n"


# Launch train code using virtual environment
python src/train.py \
    -t ${train_dir} \
    -v ${valid_dir} \
    --target-dir ${target_dir} \
    -r ${redux} \
    -n ${noise} \
    -p ${train_param} \
    --ckpt-save-path "${ckpt_save}" \
    --report-interval ${report} \
    -ch ${channels} \
    --nb-epochs ${epochs} \
    -b ${batch_size} \
    -l ${loss_fun} \
    --cuda \
    --paired-targets \
    --verbose \
    --load-ckpt "${train_ckpt}"


exit_code="$?"
echo -e "Training ended with exit code: ${exit_code}"


end=$(date +%s)
runtime_hours=$(((end-start)/3600))
runtime_minutes=$((((end-start)%3600)/60))
runtime_seconds=$((((end-start)%3600)%60))
echo -e "\nBatch job runtime was ${runtime_hours}h:${runtime_minutes}m:${runtime_seconds}s.\n "
